name: Build iOS
on: [push]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        npx cap sync ios
        
    - name: Install CocoaPods dependencies
      run: |
        cd ios/App
        sudo gem install cocoapods
        pod install
        
    - name: Build iOS app
      run: |
        cd ios/App
        xcodebuild build -workspace App.xcworkspace -scheme App -destination 'generic/platform=iOS' -configuration Debug CODE_SIGNING_ALLOWED=NO
